numpy 的常用方法

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
np.abs?

In [ ]:
lst = [3.13, 2.14, 0, 1, 2]
nd1 = np.array(lst)
print(nd1)
print(type(nd1))

In [ ]:
lst = [
    [3.14, 2.12, 0, 1, 2],
    [1, 2, 3, 4, 5],
]
nd2 = np.array(lst)
print(nd2)
print(type(nd2))

常用的随机函数
![随机函数](https://res.weread.qq.com/wrepub/epub_26858491_4)

In [ ]:
nd3 = np.random.random([3, 3])
print(nd3)
print(nd3.shape)

常用的特殊矩阵函数
![特殊矩阵函数](https://res.weread.qq.com/wrepub/epub_26858491_5)

In [ ]:
nd4 = np.random.random([5, 5])
np.savetxt(X=nd4, fname="data.txt")  # 暂存到文件中
nd5 = np.loadtxt('data.txt')  # 从文件中读取
print(nd5)

In [ ]:
print(np.arange(10))  # 类似于 range
print(np.arange(1, 3, 0.3))

In [ ]:
print(np.linspace(0, 10, 10)) # 生成线性等分, 因为会包含数据的起点和终点, 10 是最后生成的数量, 所以其实每一分是 (10-0)/(10-1)
print(np.linspace(0, 10, 11))

In [ ]:
x = np.arange(0, 10)
y = np.logspace(0, 10, 10)
print(x)
print(y)
plt.plot(x, y)
plt.show()

In [ ]:
np.random.seed(2019)
nd6 = np.random.random([10])
print(nd6)
print(nd6[3])
print(nd6[1:6:2])
print(nd6[::-2])

In [ ]:
nd7 = np.arange(25).reshape([5, 5])
print(nd7)
print(nd7[1:3, :])  # 指定的行
print(nd7[:, 1:3])  # 指定的列
print(nd7[1:3, 1:3])

In [ ]:
print(nd7[(nd7>3)&(nd7<10)])  # 值在指定范围内的数据

In [56]:
nd8 = np.arange(25)
c1 = np.random.choice(nd8, size=(3, 4))  # 随机抽取指定的数据, 形状是 (3, 4)
c2 = np.random.choice(nd8, size=(3, 4), replace=False)  # 不能重复抽取
c3 = np.random.choice(nd8, size=(3, 4), p=nd8/np.sum(nd8))  # p 参数指定抽取的概率
print(c1)
print(c2)
print(c3)

[[13 18 22 22]
 [17  1 14 19]
 [16 14 17 16]]
[[ 4 11 22 17]
 [ 3  5 19 12]
 [ 1 23  8 13]]
[[18 20 19 16]
 [13 20 20 16]
 [24 16 21 17]]


对应元素相乘（Element-Wise Product）是两个矩阵中对应元素乘积。np.multiply函数用于数组或矩阵对应元素相乘，输出与相乘数组或矩阵的大小一致

In [ ]:
A = np.array([[1, 2], [-1, 4]])
B = np.array([[2, 0], [3, 4]])
print(A*B)  # 逐元素相乘
print(np.multiply(A, B))

In [ ]:
print(A*2.0)

In [ ]:
X = np.random.rand(2,3)-0.5
def softmoid(x):
    return 1/(1+np.exp(-x))
def relu(x):
    return np.maximum(0, x)
def softmax(xf):
    return np.exp(x)/np.sum(np.exp(x))
print("输入参数 X:\n", X)
print("softmoid:\n", softmoid(X))
print("relu:\n", relu(X))
print("softmax:\n", softmax(X))

点积运算（Dot Product）又称为内积，在Numpy用np.dot表示
![点积图解](https://res.weread.qq.com/wrepub/epub_26858491_8)

In [55]:
X1 = np.array([[1, 2], [3, 4]])
X2 = np.array([[5, 6, 7], [8, 9 , 10]])
X3 = np.dot(X1, X2)
print(X3)

[[21 24 27]
 [47 54 61]]


更改形状的常用函数
![更改形状](https://res.weread.qq.com/wrepub/epub_26858491_9)

In [61]:
nd = np.arange(10)
print(nd)
print(nd.reshape(2, 5))
print(nd.reshape(5, -1))  # 使用 -1 来自动计算其他维度
print(nd.reshape(-1, 5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [66]:
nd = np.arange(10)
print(nd)
print(nd.resize(2, 5))  # 修改向量本身, 而不是返回新值
print(nd)

[0 1 2 3 4 5 6 7 8 9]
None
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [67]:
nd = np.arange(12).reshape(3, 4)
print(nd)
print(nd.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [85]:
nd = np.arange(6).reshape(2, -1)
print(nd)
print(nd.ravel('F'))  # 按列优先展平
print(nd.ravel())  # 按行优先展平
# https://www.geeksforgeeks.org/differences-flatten-ravel-numpy/
print(np.ravel(nd))
print(np.ravel(nd, 'F'))

[[0 1 2]
 [3 4 5]]
[0 3 1 4 2 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 3 1 4 2 5]


In [86]:
nd = np.arange(12).reshape(3, 4)
print(nd)
print(nd.flatten())  # 将矩阵转换为向量

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [90]:
nd = np.arange(3).reshape(3, 1)
print(nd.shape)
print(nd.squeeze().shape)  # 用来降维, 将矩阵中含 1 的维度去掉

(3, 1)
(3,)


In [88]:
nd = np.arange(24).reshape(2, 3, 4)
print(nd.shape)
print(nd.transpose(1, 2, 0).shape)  # 进行轴对换

(2, 3, 4)
(3, 4, 2)


合并数组的函数
![合并数组](https://res.weread.qq.com/wrepub/epub_26858491_10)

In [91]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.append(a, b)
print(c)

[1 2 3 4 5 6]


In [94]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(2, 3)
c = np.append(a, b, axis=0)  # 按行合并
print(c.shape)
print(c)
d = np.append(a, b, axis=1)  # 按列合并
print(d.shape)
print(d)

(4, 3)
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
(2, 6)
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [110]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

c = np.concatenate((a, b), axis=0)  # 按行合并
print(a.shape, b.shape, c.shape)
print(c)


d = np.concatenate((a, b.T), axis=1)  # 按列合并. 合并的时候其他维度要相等, 所以使用 b.T
print(a.shape, b.T.shape, d.shape)
print(d)

(2, 2) (1, 2) (3, 2)
[[1 2]
 [3 4]
 [5 6]]
(2, 2) (2, 1) (2, 3)
[[1 2 5]
 [3 4 6]]


In [119]:
a = np.array([[1, 2, 1], [3, 4, 2]])
b = np.array([[5, 6, 1], [7, 8, 4]])
c = np.stack((a, b), axis=0)  # 沿着指定的轴叠加数组或矩阵
print(c)
print(a.shape, b.shape, c.shape)

[[[1 2 1]
  [3 4 2]]

 [[5 6 1]
  [7 8 4]]]
(2, 3) (2, 3) (2, 2, 3)


In [121]:
data_train = np.random.randn(10000, 2, 3)
print(data_train.shape)
np.random.shuffle(data_train)
batch_size = 100
for i in range(0, len(data_train), batch_size):
    x_batch_sum = np.sum(data_train[i:i+batch_size])

(10000, 2, 3)


通用函数
![通用函数](https://res.weread.qq.com/wrepub/epub_26858491_11)

广播机制的规则:

1. 让所有输入数组都向其中shape最长的数组看齐，不足的部分则通过在<mark>前面</mark>加1补齐
2. 输出数组的shape是输入数组shape的各个轴上的最大值
3. 如果输入数组的某个轴和输出数组的对应轴的长度相同或者某个轴的长度为1时，这个数组能被用来计算，否则出错
4. 当输入数组的某个轴的长度为1时，沿着此轴运算时都用（或复制）此轴上的第一组值

![](https://res.weread.qq.com/wrepub/epub_26858491_12)

In [127]:
# 广播机制示例
A = np.arange(0, 40, 10).reshape(4, 1)
B = np.arange(0, 3)
C = A + B
print(A, A.shape)
print(B, B.shape)
print(C, C.shape)

[[ 0]
 [10]
 [20]
 [30]] (4, 1)
[0 1 2] (3,)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]] (4, 3)
