我感觉我一直在学习 torch, 却从来没有真正掌握它

In [1]:
import torch

In [2]:
# 获取一个 64 bit 的随机数
torch.seed()

260727154559900

In [11]:
# 手动设置随机种子
torch.manual_seed(11)

In [12]:
# 获取当前的随机种子
torch.initial_seed()

11

In [19]:
# 获取随机数生成器的状态
torch.get_rng_state()

tensor([11,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)

In [14]:
# 设置随机数生成器的状态
torch.set_rng_state(torch.get_rng_state())

In [22]:
a = torch.randint(1, 10, (2, 3))
a

tensor([[6, 7, 8],
        [6, 8, 7]])

In [24]:
# 求所有元素的乘积
torch.prod(a)

tensor(112896)

In [30]:
# 求总和, 也可以对某一维度进行求和, 那个维度会消失, 除非用 keepdim=True 保留下来
print(torch.sum(a))
print(torch.sum(a, dim=0))
print(torch.sum(a, dim=1))
print(torch.sum(a, dim=0, keepdim=True))
print(torch.sum(a, dim=1, keepdim=True))

tensor(42)
tensor([12, 15, 15])
tensor([21, 21])
tensor([[12, 15, 15]])
tensor([[21],
        [21]])


In [32]:
# 求平均值, 也有和 torch.sum 类似的操作
torch.mean(a.to(torch.float64))

tensor(7., dtype=torch.float64)

In [33]:
# 求最大值, 也有和 torch.sum 类似的操作
torch.max(a)

tensor(8)

In [34]:
# 求最小值, 也有和 torch.sum 类似的操作
torch.min(a)

tensor(6)

In [35]:
# 求中位数, 也有和 torch.sum 类似的操作
torch.median(a)

tensor(7)

In [36]:
# 求众数, 也有和 torch.sum 类似的操作
torch.mode(a)

torch.return_types.mode(
values=tensor([6, 6]),
indices=tensor([0, 0]))

In [38]:
# 求方差, 也有和 torch.sum 类似的操作
torch.var(a.to(torch.float64))

tensor(0.8000, dtype=torch.float64)

In [39]:
# 求方差, 也有和 torch.sum 类似的操作
torch.std(a.to(torch.float64))

tensor(0.8944, dtype=torch.float64)

In [42]:
a = torch.rand((2, 3))
b = torch.rand((2, 3))
print(a)
print(b)

tensor([[0.8775, 0.1626, 0.2438],
        [0.3382, 0.8847, 0.0763]])
tensor([[0.9900, 0.1944, 0.4256],
        [0.4382, 0.2988, 0.8474]])


In [43]:
# 矩阵对应元素的加法
print(a + b)
print(torch.add(a, b))

tensor([[1.8675, 0.3570, 0.6694],
        [0.7764, 1.1835, 0.9236]])
tensor([[1.8675, 0.3570, 0.6694],
        [0.7764, 1.1835, 0.9236]])


In [50]:
# 将结果输出到另一个 tensor 上
c = torch.Tensor(2, 3)
torch.add(a, b, out=c)
print(c)
# 直接使用 tensor 的 add 方法
b.add(a)

tensor([[1.8675, 0.3570, 0.6694],
        [0.7764, 1.1835, 0.9236]])


tensor([[1.8675, 0.3570, 0.6694],
        [0.7764, 1.1835, 0.9236]])

In [51]:
# 矩阵对应元素的减法
print(a - b)
print(torch.sub(a, b))

tensor([[-0.1125, -0.0318, -0.1817],
        [-0.1000,  0.5860, -0.7711]])
tensor([[-0.1125, -0.0318, -0.1817],
        [-0.1000,  0.5860, -0.7711]])


In [52]:
# 矩阵对应元素相乘
print(a * b)
print(torch.mul(a, b))

tensor([[0.8688, 0.0316, 0.1038],
        [0.1482, 0.2643, 0.0646]])
tensor([[0.8688, 0.0316, 0.1038],
        [0.1482, 0.2643, 0.0646]])


In [53]:
# 矩阵对应元素相除
print(a / b)
print(torch.div(a, b))

tensor([[0.8863, 0.8365, 0.5729],
        [0.7717, 2.9612, 0.0900]])
tensor([[0.8863, 0.8365, 0.5729],
        [0.7717, 2.9612, 0.0900]])


In [54]:
# 矩阵对应元素的幂运算
print(a ** 2)
print(a.pow(2))

tensor([[0.7700, 0.0264, 0.0594],
        [0.1144, 0.7828, 0.0058]])
tensor([[0.7700, 0.0264, 0.0594],
        [0.1144, 0.7828, 0.0058]])


In [59]:
# 矩阵对应元素的平方根
print(a.sqrt())
# 矩阵对应元素的平方根的倒数
print(a.rsqrt())

tensor([[0.9368, 0.4033, 0.4938],
        [0.5815, 0.9406, 0.2761]])
tensor([[1.0675, 2.4798, 2.0253],
        [1.7196, 1.0631, 3.6214]])


In [60]:
# 矩阵对应元素的对数
print(torch.log2(a))
print(torch.log10(a))
print(torch.log(a))

tensor([[-0.1885, -2.6204, -2.0362],
        [-1.5642, -0.1767, -3.7131]])
tensor([[-0.0567, -0.7888, -0.6130],
        [-0.4709, -0.0532, -1.1177]])
tensor([[-0.1307, -1.8163, -1.4114],
        [-1.0842, -0.1225, -2.5737]])


In [61]:
# 向下取整
print(a.floor())
# 向上取整
print(a.ceil())
# 四舍五入
print(a.round())
# 提取整数部分
print(a.trunc())
# 提取小数部分
print(a.frac())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8775, 0.1626, 0.2438],
        [0.3382, 0.8847, 0.0763]])
