torch 的自动微分和反向传播

In [1]:
import torch

In [39]:
x = torch.Tensor([2])
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
# 实现前向传播
y = torch.mul(w, x)  # w*x
z = torch.add(y, b)  # y+b

In [7]:
print(x.requires_grad, x.is_leaf)
print(w.requires_grad, w.is_leaf)
print(b.requires_grad, b.is_leaf)
print(y.requires_grad, y.is_leaf)
print(z.requires_grad, z.is_leaf)

False True
True True
True True
True False
True False


In [10]:
print(x.grad_fn)
print(w.grad_fn)
print(b.grad_fn)
print(y.grad_fn)
print(z.grad_fn)

None
None
None


In [38]:
# z.backward()
z.backward(retain_graph=True)
print(x.grad)
print(w.grad)
print(b.grad)
print(y.grad)
print(z.grad)

None
tensor([48.])
tensor([24.])
None
None


In [40]:
x = torch.tensor([[2, 3]], dtype=torch.float, requires_grad=True)
J = torch.zeros(2, 2)  # Jacobian 矩阵
y = torch.zeros(1, 2)
y[0, 0] = x[0, 0] ** 2 + 3 * x[0, 1]
y[0, 1] = x[0, 1] ** 2 + 2 * x[0, 0]
print(y)

tensor([[13., 13.]], grad_fn=<CopySlices>)


In [41]:
y.backward(torch.Tensor([[1, 0]]), retain_graph=True)
J[0] = x.grad
x.grad = torch.zeros_like(x.grad)
y.backward(torch.Tensor([[0, 1]]))
J[1] = x.grad
print(J)

tensor([[4., 3.],
        [2., 6.]])
