torch 的 tensor 介绍

In [1]:
import torch

1. 不修改自身数据, 返回一个新的 Tensor, 如 x.add(y)
2. 修改自身数据, 如 x.add_(y), 运行符带下划线后缀

In [3]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = x.add(y)  # 不修改 x 的数据
print(z)
print(x)
x.add_(y)  # 就地版本, 更新 x 的数据
print(x)

tensor([4, 6])
tensor([1, 2])
tensor([4, 6])


创建 Tensor
![](https://res.weread.qq.com/wrepub/epub_26858491_22)

In [12]:
print(torch.Tensor([1, 2, 3, 4]))
print(torch.Tensor(2, 3))
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(t)
print(t.size())
print(t.shape)
print(torch.Tensor(t.shape))

tensor([1., 2., 3., 4.])
tensor([[6.6280e-10, 4.1261e-08, 1.0386e+21],
        [2.0314e+20, 4.3439e-05, 6.4536e-10]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.Size([2, 3])
tensor([[0.0000e+00, 0.0000e+00, 8.4078e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])


修改形状
![修改形状](https://res.weread.qq.com/wrepub/epub_26858491_23)

In [18]:
x = torch.randn(2, 3)
print(x)
print(x.size())
print(x.dim())
print(x.view(3,2))
y = x.view(-1)
print(y)
print(y.shape)
z = torch.unsqueeze(y, 0)  # 在第一维度上增加一个 1
print(z)
print(z.shape)
print(z.numel())

tensor([[-0.0498,  0.7371, -0.3035],
        [ 1.1849,  1.3938,  1.2716]])
torch.Size([2, 3])
2
tensor([[-0.0498,  0.7371],
        [-0.3035,  1.1849],
        [ 1.3938,  1.2716]])
tensor([-0.0498,  0.7371, -0.3035,  1.1849,  1.3938,  1.2716])
torch.Size([6])
tensor([[-0.0498,  0.7371, -0.3035,  1.1849,  1.3938,  1.2716]])
torch.Size([1, 6])
6


选择操作
![选择操作](https://res.weread.qq.com/wrepub/epub_26858491_24)

In [39]:
torch.manual_seed(100)  # 设置固定的随机种子
x = torch.randn(2, 3)
print(x)
print(x[0, :])  # 第一行的所有数据
print(x[:, -1])  # 最后一列的所有数据
mask = x > 0  # 生成 bool 张量
print(mask)
y = torch.masked_select(x, mask)
print(y)
print(torch.nonzero(mask))  # 获取非零下标, 即行列索引
# 获取指定索引对应的值, 输出根据以下规则得到
# out[i][j] = input[index[i][j]][j]  # if dim == 0
# out[i][j] = input[i][index[i][j]]  # if dim == 1
index = torch.LongTensor([[0, 1, 1]])
print(index)
print(torch.gather(x, 0, index))  # dim == 0
index = torch.LongTensor([[0, 1, 1], [1, 1, 1]])
a = torch.gather(x , 1, index)  # dim == 1
print(a)
z = torch.zeros(2, 3)
print(z)
b = torch.scatter(z, 1, index, a)
print(b)

tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134]])
tensor([ 0.3607, -0.2859, -0.3938])
tensor([-0.3938, -2.3134])
tensor([[ True, False, False],
        [ True, False, False]])
tensor([0.3607, 0.2429])
tensor([[0, 0],
        [1, 0]])
tensor([[0, 1, 1]])
tensor([[ 0.3607, -1.3833, -2.3134]])
tensor([[ 0.3607, -0.2859, -0.2859],
        [-1.3833, -1.3833, -1.3833]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.3607, -0.2859,  0.0000],
        [ 0.0000, -1.3833,  0.0000]])


In [43]:
# torch 的广播机制示例
import numpy as np 
A = np.arange(0, 40, 10).reshape(4, 1)
B = np.arange(0, 3)
A1 = torch.from_numpy(A)
B1 = torch.from_numpy(B)
print(A1)
print(B1)
C = A1 + B1
print(C)

# 手动配置, 结果为每个轴上最大的, 所以结果的形状为 (4, 3)
B2 = B1.unsqueeze(0)  # B2 的形状为 (1, 3)
A2 = A1.expand(4, 3)  # 重复数组, 变成 (4, 3)
B3 = B2.expand(4, 3)  # 重复数组, 变成 (4, 3)
print(A2)
print(B3)
C1 = A2 + B3
print(C1)

tensor([[ 0],
        [10],
        [20],
        [30]], dtype=torch.int32)
tensor([0, 1, 2], dtype=torch.int32)
tensor([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]], dtype=torch.int32)
tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30]], dtype=torch.int32)
tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]], dtype=torch.int32)
tensor([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]], dtype=torch.int32)


逐元素操作
![逐元素操作](https://res.weread.qq.com/wrepub/epub_26858491_25)

归并操作
![归并操作](https://res.weread.qq.com/wrepub/epub_26858491_26)

In [44]:
a = torch.linspace(0, 10, 6)
a = a.view((2, 3))
print(a)
b = a.sum(dim=0)
print(b)
b = a.sum(dim=0, keepdim=True)
print(b)

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
tensor([ 6., 10., 14.])
tensor([[ 6., 10., 14.]])


比较函数
![比较函数](https://res.weread.qq.com/wrepub/epub_26858491_27)

矩阵操作
![矩阵操作](https://res.weread.qq.com/wrepub/epub_26858491_28)

In [49]:
a = torch.tensor([2, 3])
b = torch.tensor([3, 4])
print(torch.dot(a, b))
x = torch.randint(10, (2, 3))
y = torch.randint(6, (3, 4))
print(torch.mm(x, y))
x = torch.randint(10, (2, 2, 3))
y = torch.randint(10, (2, 3, 4))
print(x)
print(y)
print(torch.bmm(x, y))
print(torch.bmm(x, y).shape)

tensor(18)
tensor([[ 6,  8,  4,  0],
        [26, 43, 24,  0]])
tensor([[[2, 5, 3],
         [6, 7, 8]],

        [[1, 2, 3],
         [2, 7, 9]]])
tensor([[[3, 9, 7, 7],
         [5, 9, 2, 2],
         [4, 8, 9, 6]],

        [[1, 4, 5, 6],
         [0, 4, 5, 8],
         [0, 8, 9, 6]]])
tensor([[[ 43,  87,  51,  42],
         [ 85, 181, 128, 104]],

        [[  1,  36,  42,  40],
         [  2, 108, 126, 122]]])
torch.Size([2, 2, 4])


PyTorch 和 Numpy 函数对照表
![](https://res.weread.qq.com/wrepub/epub_26858491_29)