常用的激活函数

![常用的激活函数](https://res.weread.qq.com/wrepub/epub_26858491_81)

常用的损失函数
- MSELoss 用于回归
- CrossEntropyLoss 用于分类


In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(10)

In [2]:
loss = nn.MSELoss(reduction='mean')
input = torch.randn(1, 2, requires_grad=True)
print(input)
target = torch.randn(1, 2)
print(target)

output = loss(input, target)
print(output)
output.backward()

tensor([[-0.6014, -1.0122]], requires_grad=True)
tensor([[-0.3023, -1.2277]])
tensor(0.0680, grad_fn=<MseLossBackward>)


In [5]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
print(input)
print(target)

output = loss(input, target)
print(output)
output.backward()

tensor([[ 0.1914,  0.2295, -0.7246, -0.8332,  0.8764],
        [-0.6386,  0.3057, -0.5610, -0.5233, -0.0610],
        [-0.4628,  1.3686,  2.0509, -0.6301, -1.1665]], requires_grad=True)
tensor([1, 1, 3])
tensor(1.9378, grad_fn=<NllLossBackward>)


常见的优化器

- 动量 SGD
- NAG (SGD 的优化版)
- AdaGrad
- RMSProp (AdaGrad 的优化版)
- Adam (带动量项的 RMSProp)

单机多 GPU 主要使用 DataParallel 函数，多主机多GPU 使用 DistributedParallel