# 安装 PyTorch

https://pytorch.org/

## 检查 GPU 兼容性

https://developer.nvidia.com/cuda-gpus

## 安装 CUDA

https://developer.nvidia.com/cuda-zone

去这边下载, 选择的时候选离线包, 即 `exe (local)`.

## 安装 cuDNN

https://developer.nvidia.com/cudnn

注意选择和 CUDA 对应的版本. **需要注册并登陆**.

https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#install-windows

安装文档, 基本操作如下:

> Copy <installpath>\cuda\bin\cudnn64_7.6.5.32.dll to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin.
>
> Copy <installpath>\cuda\ include\cudnn.h to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include.
> 
> Copy <installpath>\cuda\lib\x64\cudnn.lib to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64.

## 安装 pytorch

https://pytorch.org/get-started/locally/

去找对应的版本, 选定之后会给出对应的安装命令.

conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

## 验证是否安装成功

```python
import torch
x = torch.tensor([10.0])
x = x.cuda()
print(x)
y = torch.randn(2, 3)
y = y.cuda()
print(y)
z = x + y
print(z)

from torch.backends import cudnn
print(cudnn.is_acceptable(x))
print(cudnn.version())
print(cudnn.is_acceptable(torch.cuda.FloatTensor(1)))
print(cudnn.version())
```



In [1]:
import torch
print(torch.cuda.is_available())

x = torch.tensor([10.0])
x = x.cuda()
print(x)
y = torch.randn(2, 3)
y = y.cuda()
print(y)
z = x + y
print(z)

from torch.backends import cudnn
print(cudnn.is_acceptable(x))
print(cudnn.version())
print(cudnn.is_acceptable(torch.cuda.FloatTensor(1)))
print(cudnn.version())

True
tensor([10.], device='cuda:0')
tensor([[-0.0344,  1.8270, -1.1743],
        [-1.7450, -0.5376,  0.9639]], device='cuda:0')
tensor([[ 9.9656, 11.8270,  8.8257],
        [ 8.2550,  9.4624, 10.9639]], device='cuda:0')
True
7501
True
7501
